---
title: My dynamic report
output: html_fragment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, error=FALSE)

```


## How good at sudoku am I?

You need to change the contents of this Rmd! Replace the R code and markdown give below in this template document.

```{r}
library(tidyverse)
logged_data<-read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQzNzzgwQsO7coptAAHSwmyIOmMlYL7RoFV0ei_UVfKiqkxnzBBpfqcPtp-fo8bq1-1iEcf8LlMeGWx/pub?gid=1304239942&single=true&output=csv")
latest_data<-logged_data%>%rename(Difficulty = 3,
                                  Time = 4,
                                  Mistakes = 5)

paste("The mean time taken for sudoku games is", mean(latest_data$Time), "seconds")

ggplot(data = latest_data) + geom_bar(aes(x=Time)) +geom_vline(xintercept = mean(latest_data$Time), col="red")

```

```{r}
paste("The mean number of mistakes made in each sudoku game is", mean(latest_data$Mistakes))
ggplot(data=latest_data) + geom_bar(aes(x=Mistakes)) + geom_vline(xintercept=mean(latest_data$Mistakes), col="purple")

```
